"""NSE Stock Universe — ~145 stocks across Large, Mid, Small caps.
Delisted stocks removed. Aliases added for Telegram /stock lookup.
Low-price stocks added for small capital investors (₹15-20K).
"""

STOCK_UNIVERSE = {
    # ── NIFTY 50 (Large Cap) ──────────────────────────────────────────────
    "RELIANCE.NS":  {"name": "Reliance Industries", "sector": "Energy", "cap": "Large"},
    "TCS.NS":       {"name": "Tata Consultancy", "sector": "IT", "cap": "Large"},
    "HDFCBANK.NS":  {"name": "HDFC Bank", "sector": "Banking", "cap": "Large"},
    "INFY.NS":      {"name": "Infosys", "sector": "IT", "cap": "Large"},
    "ICICIBANK.NS": {"name": "ICICI Bank", "sector": "Banking", "cap": "Large"},
    "HINDUNILVR.NS":{"name": "Hindustan Unilever", "sector": "FMCG", "cap": "Large"},
    "SBIN.NS":      {"name": "State Bank of India", "sector": "Banking", "cap": "Large"},
    "BHARTIARTL.NS":{"name": "Bharti Airtel", "sector": "Telecom", "cap": "Large"},
    "KOTAKBANK.NS": {"name": "Kotak Mahindra Bank", "sector": "Banking", "cap": "Large"},
    "ITC.NS":       {"name": "ITC Limited", "sector": "FMCG", "cap": "Large"},
    "LT.NS":        {"name": "Larsen & Toubro", "sector": "Infrastructure", "cap": "Large"},
    "AXISBANK.NS":  {"name": "Axis Bank", "sector": "Banking", "cap": "Large"},
    "BAJFINANCE.NS":{"name": "Bajaj Finance", "sector": "Finance", "cap": "Large"},
    "ASIANPAINT.NS":{"name": "Asian Paints", "sector": "Consumer", "cap": "Large"},
    "MARUTI.NS":    {"name": "Maruti Suzuki", "sector": "Auto", "cap": "Large"},
    "TITAN.NS":     {"name": "Titan Company", "sector": "Consumer", "cap": "Large"},
    "SUNPHARMA.NS": {"name": "Sun Pharma", "sector": "Pharma", "cap": "Large"},
    "WIPRO.NS":     {"name": "Wipro", "sector": "IT", "cap": "Large"},
    "ULTRACEMCO.NS":{"name": "UltraTech Cement", "sector": "Cement", "cap": "Large"},
    "HCLTECH.NS":   {"name": "HCL Technologies", "sector": "IT", "cap": "Large"},
    "NTPC.NS":      {"name": "NTPC Limited", "sector": "Power", "cap": "Large"},
    "POWERGRID.NS": {"name": "Power Grid Corp", "sector": "Power", "cap": "Large"},
    "TATASTEEL.NS": {"name": "Tata Steel", "sector": "Metals", "cap": "Large"},
    "ONGC.NS":      {"name": "ONGC", "sector": "Energy", "cap": "Large"},
    "JSWSTEEL.NS":  {"name": "JSW Steel", "sector": "Metals", "cap": "Large"},
    "M&M.NS":       {"name": "Mahindra & Mahindra", "sector": "Auto", "cap": "Large"},
    "ADANIENT.NS":  {"name": "Adani Enterprises", "sector": "Conglomerate", "cap": "Large"},
    "ADANIPORTS.NS":{"name": "Adani Ports", "sector": "Infrastructure", "cap": "Large"},
    "COALINDIA.NS": {"name": "Coal India", "sector": "Mining", "cap": "Large"},
    "BAJAJFINSV.NS":{"name": "Bajaj Finserv", "sector": "Finance", "cap": "Large"},
    "TECHM.NS":     {"name": "Tech Mahindra", "sector": "IT", "cap": "Large"},
    "DRREDDY.NS":   {"name": "Dr Reddy's Labs", "sector": "Pharma", "cap": "Large"},
    "CIPLA.NS":     {"name": "Cipla", "sector": "Pharma", "cap": "Large"},
    "HDFCLIFE.NS":  {"name": "HDFC Life Insurance", "sector": "Insurance", "cap": "Large"},
    "SBILIFE.NS":   {"name": "SBI Life Insurance", "sector": "Insurance", "cap": "Large"},
    "DIVISLAB.NS":  {"name": "Divi's Laboratories", "sector": "Pharma", "cap": "Large"},
    "GRASIM.NS":    {"name": "Grasim Industries", "sector": "Cement", "cap": "Large"},
    "BPCL.NS":      {"name": "BPCL", "sector": "Energy", "cap": "Large"},
    "BRITANNIA.NS": {"name": "Britannia Industries", "sector": "FMCG", "cap": "Large"},
    "EICHERMOT.NS": {"name": "Eicher Motors", "sector": "Auto", "cap": "Large"},
    "INDUSINDBK.NS":{"name": "IndusInd Bank", "sector": "Banking", "cap": "Large"},
    "APOLLOHOSP.NS":{"name": "Apollo Hospitals", "sector": "Healthcare", "cap": "Large"},
    "NESTLEIND.NS": {"name": "Nestle India", "sector": "FMCG", "cap": "Large"},
    "TATACONSUM.NS":{"name": "Tata Consumer", "sector": "FMCG", "cap": "Large"},
    "HEROMOTOCO.NS":{"name": "Hero MotoCorp", "sector": "Auto", "cap": "Large"},
    "HINDALCO.NS":  {"name": "Hindalco", "sector": "Metals", "cap": "Large"},
    "BAJAJ-AUTO.NS":{"name": "Bajaj Auto", "sector": "Auto", "cap": "Large"},
    "VEDL.NS":      {"name": "Vedanta", "sector": "Metals", "cap": "Large"},
    "IOC.NS":       {"name": "Indian Oil Corp", "sector": "Energy", "cap": "Large"},

    # ── MID CAP STOCKS ────────────────────────────────────────────────────
    "PIDILITIND.NS":{"name": "Pidilite Industries", "sector": "Chemicals", "cap": "Mid"},
    "DABUR.NS":     {"name": "Dabur India", "sector": "FMCG", "cap": "Mid"},
    "GODREJCP.NS":  {"name": "Godrej Consumer", "sector": "FMCG", "cap": "Mid"},
    "BERGEPAINT.NS":{"name": "Berger Paints", "sector": "Consumer", "cap": "Mid"},
    "UNITDSPR.NS":  {"name": "United Spirits", "sector": "Consumer", "cap": "Mid"},
    "HAVELLS.NS":   {"name": "Havells India", "sector": "Electricals", "cap": "Mid"},
    "VOLTAS.NS":    {"name": "Voltas", "sector": "Consumer Durables", "cap": "Mid"},
    "TRENT.NS":     {"name": "Trent Limited", "sector": "Retail", "cap": "Mid"},
    "MUTHOOTFIN.NS":{"name": "Muthoot Finance", "sector": "Finance", "cap": "Mid"},
    "CHOLAFIN.NS":  {"name": "Cholamandalam Fin", "sector": "Finance", "cap": "Mid"},
    "JINDALSTEL.NS":{"name": "Jindal Steel", "sector": "Metals", "cap": "Mid"},
    "NMDC.NS":      {"name": "NMDC Limited", "sector": "Mining", "cap": "Mid"},
    "SAIL.NS":      {"name": "SAIL", "sector": "Metals", "cap": "Mid"},
    "UNITDSPR.NS":  {"name": "United Spirits", "sector": "Consumer", "cap": "Mid"},
    "CANBK.NS":     {"name": "Canara Bank", "sector": "Banking", "cap": "Mid"},
    "PPLPHARMA.NS": {"name": "Piramal Pharma", "sector": "Pharma", "cap": "Mid"},
    "BANKBARODA.NS":{"name": "Bank of Baroda", "sector": "Banking", "cap": "Mid"},
    "PNB.NS":       {"name": "Punjab National Bank", "sector": "Banking", "cap": "Mid"},
    "FEDERALBNK.NS":{"name": "Federal Bank", "sector": "Banking", "cap": "Mid"},
    "IDFCFIRSTB.NS":{"name": "IDFC First Bank", "sector": "Banking", "cap": "Mid"},
    "AUROPHARMA.NS":{"name": "Aurobindo Pharma", "sector": "Pharma", "cap": "Mid"},
    "LUPIN.NS":     {"name": "Lupin Limited", "sector": "Pharma", "cap": "Mid"},
    "BIOCON.NS":    {"name": "Biocon", "sector": "Pharma", "cap": "Mid"},
    "TORNTPHARM.NS":{"name": "Torrent Pharma", "sector": "Pharma", "cap": "Mid"},
    "ALKEM.NS":     {"name": "Alkem Labs", "sector": "Pharma", "cap": "Mid"},
    "MPHASIS.NS":   {"name": "Mphasis", "sector": "IT", "cap": "Mid"},
    "LTIM.NS":      {"name": "LTIMindtree", "sector": "IT", "cap": "Mid"},
    "COFORGE.NS":   {"name": "Coforge", "sector": "IT", "cap": "Mid"},
    "PERSISTENT.NS":{"name": "Persistent Systems", "sector": "IT", "cap": "Mid"},
    "TATAELXSI.NS": {"name": "Tata Elxsi", "sector": "IT", "cap": "Mid"},
    "LAURUSLABS.NS":{"name": "Laurus Labs", "sector": "Pharma", "cap": "Mid"},
    "POLYCAB.NS":   {"name": "Polycab India", "sector": "Electricals", "cap": "Mid"},
    "DEEPAKNTR.NS": {"name": "Deepak Nitrite", "sector": "Chemicals", "cap": "Mid"},
    "ATUL.NS":      {"name": "Atul Limited", "sector": "Chemicals", "cap": "Mid"},
    "NAVINFLUOR.NS":{"name": "Navin Fluorine", "sector": "Chemicals", "cap": "Mid"},
    "TATAPOWER.NS": {"name": "Tata Power", "sector": "Power", "cap": "Mid"},
    "NHPC.NS":      {"name": "NHPC Limited", "sector": "Power", "cap": "Mid"},
    "IRCTC.NS":     {"name": "IRCTC", "sector": "Tourism", "cap": "Mid"},
    "IRFC.NS":      {"name": "IRFC", "sector": "Finance", "cap": "Mid"},
    "HAL.NS":       {"name": "Hindustan Aero", "sector": "Defence", "cap": "Mid"},
    "BEL.NS":       {"name": "Bharat Electronics", "sector": "Defence", "cap": "Mid"},
    "RECLTD.NS":    {"name": "REC Limited", "sector": "Finance", "cap": "Mid"},
    "PFC.NS":       {"name": "Power Finance Corp", "sector": "Finance", "cap": "Mid"},
    "ESCORTS.NS":   {"name": "Escorts Kubota", "sector": "Auto", "cap": "Mid"},
    "BALKRISIND.NS":{"name": "Balkrishna Ind", "sector": "Auto Parts", "cap": "Mid"},
    "MOTHERSON.NS": {"name": "Motherson Sumi", "sector": "Auto Parts", "cap": "Mid"},
    "PAGEIND.NS":   {"name": "Page Industries", "sector": "Textiles", "cap": "Mid"},
    "DIXON.NS":     {"name": "Dixon Technologies", "sector": "Electronics", "cap": "Mid"},
    "ETERNAL.NS":   {"name": "Zomato (Eternal)", "sector": "Tech", "cap": "Mid"},
    "PAYTM.NS":     {"name": "Paytm (One97)", "sector": "Fintech", "cap": "Mid"},
    "NYKAA.NS":     {"name": "Nykaa (FSN E-Com)", "sector": "E-Commerce", "cap": "Mid"},
    "DELHIVERY.NS": {"name": "Delhivery", "sector": "Logistics", "cap": "Mid"},

    # ── SMALL CAP STOCKS ──────────────────────────────────────────────────
    "IDEA.NS":      {"name": "Vodafone Idea", "sector": "Telecom", "cap": "Small"},
    "YESBANK.NS":   {"name": "Yes Bank", "sector": "Banking", "cap": "Small"},
    "SUZLON.NS":    {"name": "Suzlon Energy", "sector": "Energy", "cap": "Small"},
    "TRIDENT.NS":   {"name": "Trident Limited", "sector": "Textiles", "cap": "Small"},
    "RBLBANK.NS":   {"name": "RBL Bank", "sector": "Banking", "cap": "Small"},
    "MANAPPURAM.NS":{"name": "Manappuram Finance", "sector": "Finance", "cap": "Small"},
    "NATIONALUM.NS":{"name": "National Aluminium", "sector": "Metals", "cap": "Small"},
    "HINDZINC.NS":  {"name": "Hindustan Zinc", "sector": "Metals", "cap": "Small"},
    "GMRAIRPORT.NS":{"name": "GMR Airports Infra", "sector": "Infrastructure", "cap": "Small"},
    "CENTRALBK.NS": {"name": "Central Bank", "sector": "Banking", "cap": "Small"},
    "INDHOTEL.NS":  {"name": "Indian Hotels", "sector": "Hotels", "cap": "Small"},
    "GLENMARK.NS":  {"name": "Glenmark Pharma", "sector": "Pharma", "cap": "Small"},
    "IPCALAB.NS":   {"name": "IPCA Labs", "sector": "Pharma", "cap": "Small"},
    "GRANULES.NS":  {"name": "Granules India", "sector": "Pharma", "cap": "Small"},
    "RAJESHEXPO.NS":{"name": "Rajesh Exports", "sector": "Gems & Jewellery", "cap": "Small"},
    "PCJEWELLER.NS":{"name": "PC Jeweller", "sector": "Gems & Jewellery", "cap": "Small"},
    "RVNL.NS":     {"name": "RVNL", "sector": "Infrastructure", "cap": "Small"},
    "HUDCO.NS":    {"name": "HUDCO", "sector": "Finance", "cap": "Small"},
    "CESC.NS":     {"name": "CESC Limited", "sector": "Power", "cap": "Small"},
    "IEX.NS":      {"name": "Indian Energy Exch", "sector": "Exchange", "cap": "Small"},
    "CDSL.NS":     {"name": "CDSL", "sector": "Exchange", "cap": "Small"},
    "SONACOMS.NS": {"name": "Sona BLW", "sector": "Auto Parts", "cap": "Small"},
    "ROUTE.NS":    {"name": "Route Mobile", "sector": "IT", "cap": "Small"},
    "HAPPSTMNDS.NS":{"name": "Happiest Minds", "sector": "IT", "cap": "Small"},
    "KPITTECH.NS": {"name": "KPIT Technologies", "sector": "IT", "cap": "Small"},
    "TANLA.NS":    {"name": "Tanla Platforms", "sector": "IT", "cap": "Small"},
    "RATNAMANI.NS":{"name": "Ratnamani Metals", "sector": "Metals", "cap": "Small"},
    "AFFLE.NS":    {"name": "Affle India", "sector": "Tech", "cap": "Small"},
    "CLEAN.NS":    {"name": "Clean Science", "sector": "Chemicals", "cap": "Small"},
    "SJVN.NS":     {"name": "SJVN Limited", "sector": "Power", "cap": "Small"},

    # ── LOW-PRICE Stocks (₹10-300 range) for ₹15K-₹20K capital ──────────
    "RPOWER.NS":    {"name": "Reliance Power", "sector": "Power", "cap": "Small"},
    "RTNPOWER.NS":  {"name": "RattanIndia Power", "sector": "Power", "cap": "Small"},
    "RTNINDIA.NS":  {"name": "RattanIndia Enterprises", "sector": "Energy", "cap": "Small"},
    "IREDA.NS":     {"name": "IREDA", "sector": "Finance", "cap": "Small"},
    "JSWENERGY.NS": {"name": "JSW Energy", "sector": "Power", "cap": "Small"},
    "ENGINERSIN.NS":{"name": "Engineers India", "sector": "Infrastructure", "cap": "Small"},
    "NBCC.NS":      {"name": "NBCC India", "sector": "Infrastructure", "cap": "Small"},
    "HFCL.NS":      {"name": "HFCL Limited", "sector": "Telecom", "cap": "Small"},
    "COCHINSHIP.NS":{"name": "Cochin Shipyard", "sector": "Defence", "cap": "Small"},
    "MAZDOCK.NS":   {"name": "Mazagon Dock", "sector": "Defence", "cap": "Small"},
}

SECTORS = sorted(set(v["sector"] for v in STOCK_UNIVERSE.values()))

# ═══════════════════════════════════════════════════════════════════════════
# TICKER ALIASES — Maps short names / old names → .NS ticker
# ═══════════════════════════════════════════════════════════════════════════
TICKER_ALIASES = {
    "RELIANCE": "RELIANCE.NS", "RIL": "RELIANCE.NS",
    "TCS": "TCS.NS", "INFY": "INFY.NS", "INFOSYS": "INFY.NS",
    "HDFC": "HDFCBANK.NS", "HDFCBANK": "HDFCBANK.NS",
    "ICICI": "ICICIBANK.NS", "ICICIBANK": "ICICIBANK.NS",
    "SBIN": "SBIN.NS", "SBI": "SBIN.NS",
    "AIRTEL": "BHARTIARTL.NS", "BHARTIARTL": "BHARTIARTL.NS",
    "KOTAK": "KOTAKBANK.NS", "ITC": "ITC.NS", "LT": "LT.NS",
    "AXIS": "AXISBANK.NS", "BAJAJ": "BAJFINANCE.NS",
    "MARUTI": "MARUTI.NS", "TITAN": "TITAN.NS",
    "SUNPHARMA": "SUNPHARMA.NS", "SUN": "SUNPHARMA.NS",
    "WIPRO": "WIPRO.NS", "HCL": "HCLTECH.NS",
    "NTPC": "NTPC.NS", "POWERGRID": "POWERGRID.NS",
    "ONGC": "ONGC.NS", "MM": "M&M.NS", "MAHINDRA": "M&M.NS",
    "ADANI": "ADANIENT.NS", "COAL": "COALINDIA.NS",
    "VEDL": "VEDL.NS", "VEDANTA": "VEDL.NS", "IOC": "IOC.NS",
    "PNB": "PNB.NS", "CANARA": "CANBK.NS", "BOB": "BANKBARODA.NS",
    "FEDERAL": "FEDERALBNK.NS", "IDFC": "IDFCFIRSTB.NS",
    "HAL": "HAL.NS", "BEL": "BEL.NS", "IRCTC": "IRCTC.NS",
    "IRFC": "IRFC.NS", "TATAPOWER": "TATAPOWER.NS", "NHPC": "NHPC.NS",
    "PFC": "PFC.NS", "REC": "RECLTD.NS", "SAIL": "SAIL.NS",
    "NMDC": "NMDC.NS", "ZOMATO": "ETERNAL.NS", "PAYTM": "PAYTM.NS",
    "IDEA": "IDEA.NS", "VI": "IDEA.NS", "VODAFONE": "IDEA.NS",
    "YESBANK": "YESBANK.NS", "YES": "YESBANK.NS",
    "SUZLON": "SUZLON.NS", "TRIDENT": "TRIDENT.NS",
    "NALCO": "NATIONALUM.NS", "NATIONALUM": "NATIONALUM.NS",
    "RVNL": "RVNL.NS", "HUDCO": "HUDCO.NS", "CDSL": "CDSL.NS",
    "IEX": "IEX.NS", "IREDA": "IREDA.NS", "NBCC": "NBCC.NS",
    "HFCL": "HFCL.NS", "RPOWER": "RPOWER.NS", "RTNPOWER": "RTNPOWER.NS",
    "RTN": "RTNINDIA.NS", "RATTANINDIA": "RTNINDIA.NS", "RTNINDIA": "RTNINDIA.NS",
    "RNPOWER": "RTNPOWER.NS", "RATTANINDIAPOWER": "RTNPOWER.NS",
    "COCHINSHIP": "COCHINSHIP.NS", "MAZDOCK": "MAZDOCK.NS",
    # Old/delisted redirects
    "TATAMOTORS": "TATASTEEL.NS",
    "GMRINFRA": "GMRAIRPORT.NS", "ETERNAL": "ETERNAL.NS", "GMRAIRPORT": "GMRAIRPORT.NS",
    "PEL": "PPLPHARMA.NS", "PIRAMAL": "PPLPHARMA.NS",
    "MCDOWELL": "UNITDSPR.NS", "MCDOWELL-N": "UNITDSPR.NS",
}


def resolve_ticker(query: str):
    """Resolve user query to .NS ticker. Returns ticker or None."""
    q = query.upper().strip().replace(".NS", "")
    if f"{q}.NS" in STOCK_UNIVERSE:
        return f"{q}.NS"
    if q in TICKER_ALIASES:
        resolved = TICKER_ALIASES[q]
        if resolved in STOCK_UNIVERSE:
            return resolved
    # Fuzzy search in ticker and name
    matches = [k for k, v in STOCK_UNIVERSE.items()
               if q in k.replace(".NS","") or q in v["name"].upper()]
    return matches[0] if matches else None
